### ISSUE TITLE
Using adressable_set from aioesphomeapi

### ISSUE THREAD

**Issue by fanchlegal** [esphome/aioesphomeapi#32]
I'm trying to use aioesphomeapi from a Python program to drive some leds with fastled. The aim is to choose which color on which led i wanna to turn on. I was thinking of sending an array like this one : [ n_led, color_r, color_b, color_g , n_led_next, color_r, color_b, color_g ... ]
I'm confuse on how to do that, I try to read the documentation but i do not understand on how to add an argument on a call from aiesphomeapi and what to add on the YAML for my ESP.

Can somebody have an example or explain to me how to do it ?

Thanks

**Comment by OttoWinter** [comment]
There's no network API to set fastled values directly (there are only LightCommands, that set the state of the whole strip); you'd need to write an `api` user-defined service that gets passed the color values as parameters, then sets the LED values from there.

In python, you'd need to call that via [`execute_service`](https://github.com/esphome/aioesphomeapi/blob/master/aioesphomeapi/client.py#L381)

**Comment by fanchlegal** [comment]
Ok thanks for your answer, but how can i set the LED values from there ? That's what i do  not understand in fact.
I write something like this : 

api:
  services:
    - service: led_effect
      variables:
        my_leds: float[]
      then:
        - lambda: |-

But i'm stuck here, i do not understand how to bring all together, care to help me ?

Thanks

**Comment by OttoWinter** [comment]
Something like this should do the trick (here the RGBs are sent in separate parameters for simplicity)
```yaml
api:
  services:
  - service: led_effect
    variables:
      my_reds: float[]
      my_greens: float[]
      my_blues: float[]
    then:
    - lambda: |
        for (int i = 0; i < my_reds.size(); i++) {
          id(my_light)[i] = {my_reds[i], my_greens[i], my_blues[i]};
        }
```

APIs:
- [select LED from my_light](https://esphome.io/api/classesphome_1_1light_1_1_addressable_light.html#a522a82a1812f6bb7537c75c0ad27b76b) (`id(my_light)[i]`)
- [construct Color instance](https://esphome.io/api/structesphome_1_1_color.html#a8320eee43f0f54e19a47a2f30c12b34c) (`{my_reds[i], ...}`)
