### ISSUE TITLE
`ValueError: 6 is not a valid ClimateMode` when getting climate device entities

### ISSUE THREAD

**Issue by Quantum-cross** [esphome/aioesphomeapi#35]
I'm encountering this error enumerating the entities of my climate device.

This problem is occurring within Homeassistant as well (see logs).

`asyncio` funkiness because I'm running in Jupyter.

```Successfully installed aioesphomeapi-2.8.0```

```python
import nest_asyncio
nest_asyncio.apply()
import aioesphomeapi
import asyncio

async def main():
    """Connect to an ESPHome device and get details."""
    loop = asyncio.get_running_loop()

    # Establish connection
    api = aioesphomeapi.APIClient(loop, "prusa_enclosure.local", 6053, "")
    await api.connect(login=True)

    # Get API version of the device's firmware
    print(api.api_version)

    # Show device details
    device_info = await api.device_info()

    # List all entities of the device
    entities = await api.list_entities_services()
    for entity in entities[0]:
        print(entity)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

```Python traceback
APIVersion(major=1, minor=4)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-764d321eea0b> in <module>
     25 
     26 loop = asyncio.get_event_loop()
---> 27 loop.run_until_complete(main())

~/.venv3/lib/python3.9/site-packages/nest_asyncio.py in run_until_complete(self, future)
     68                 raise RuntimeError(
     69                     'Event loop stopped before Future completed.')
---> 70             return f.result()
     71 
     72     def _run_once(self):

/usr/lib/python3.9/asyncio/futures.py in result(self)
    199         self.__log_traceback = False
    200         if self._exception is not None:
--> 201             raise self._exception
    202         return self._result
    203 

/usr/lib/python3.9/asyncio/tasks.py in __step(***failed resolving arguments***)
    254                 # We use the `send` method directly, because coroutines
    255                 # don't have `__iter__` and `__next__` methods.
--> 256                 result = coro.send(None)
    257             else:
    258                 result = coro.throw(exc)

<ipython-input-2-764d321eea0b> in main()
     19 
     20     # List all entities of the device
---> 21     entities = await api.list_entities_services()
     22     for entity in entities[0]:
     23         print(entity)

~/.venv3/lib/python3.9/site-packages/aioesphomeapi/client.py in list_entities_services(self)
    135             for key, _ in attr.fields_dict(cls).items():
    136                 kwargs[key] = getattr(msg, key)
--> 137             entities.append(cls(**kwargs))
    138         return entities, services
    139 

~/.venv3/lib/python3.9/site-packages/aioesphomeapi/model.py in __init__(self, object_id, key, name, unique_id, supports_current_temperature, supports_two_point_target_temperature, supported_modes, visual_min_temperature, visual_max_temperature, visual_temperature_step, supports_away, supports_action, supported_fan_modes, supported_swing_modes)
      7     self.supports_two_point_target_temperature = supports_two_point_target_temperature
      8     if supported_modes is not NOTHING:
----> 9         self.supported_modes = __attr_converter_supported_modes(supported_modes)
     10     else:
     11         self.supported_modes = __attr_converter_supported_modes(__attr_factory_supported_modes())

~/.venv3/lib/python3.9/site-packages/aioesphomeapi/model.py in _convert_climate_modes(value)
    243 
    244 def _convert_climate_modes(value):
--> 245     return [ClimateMode(val) for val in value]
    246 
    247 

~/.venv3/lib/python3.9/site-packages/aioesphomeapi/model.py in <listcomp>(.0)
    243 
    244 def _convert_climate_modes(value):
--> 245     return [ClimateMode(val) for val in value]
    246 
    247 

/usr/lib/python3.9/enum.py in __call__(cls, value, names, module, qualname, type, start)
    358         """
    359         if names is None:  # simple value lookup
--> 360             return cls.__new__(cls, value)
    361         # otherwise, functional API: we're creating a new Enum type
    362         return cls._create_(

/usr/lib/python3.9/enum.py in __new__(cls, value)
    675             ve_exc = ValueError("%r is not a valid %s" % (value, cls.__qualname__))
    676             if result is None and exc is None:
--> 677                 raise ve_exc
    678             elif exc is None:
    679                 exc = TypeError(

ValueError: 6 is not a valid ClimateMode
```

```yaml
esphome:
  name: prusa_enclosure
  platform: ESP32
  board: esp32dev

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Prusa Enclosure Fallback Hotspot"
    password: ""

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: ledc
    pin: GPIO32
    id: fan_output
    frequency: "25kHz"

  - platform: template
    id: fan_output_scaled
    type: float
    write_action:
      - output.set_level:
          id: fan_output
          level: !lambda |-
                 return (state ? state*.55+.20 : 0);

light:
  - platform: monochromatic
    name: "Enclosure fan"
    output: fan_output_scaled
    gamma_correct: 1
    default_transition_length: 0s

  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO26
    num_leds: 68
    rgb_order: GRB
    name: "Enclosure light"

sensor:
  - platform: pulse_counter
    pin: GPIO33
    name: 'Fan speed'
    filters:
      - multiply: 0.5
    update_interval: 1s
        
  - platform: dht
    pin: 25
    temperature:
            name: "Enclosure temperature"
            id: "enclosure_temp"
            unit_of_measurement: "°C"
    humidity:
            name: "Enclosure humidity"
    update_interval: 1s
    model: DHT22


climate:
  - platform: pid
    name: "Enclosure PID controller"
    id: pid_enclosure
    sensor: enclosure_temp
    default_target_temperature: 26.00C
    cool_output: fan_output
    control_parameters:
        kp: 0.25000
        ki: 0.00150
        kd: 0.15000


switch:
  - platform: template
    name: "PID Autotune"
    turn_on_action:
      - climate.pid.autotune:
              id: pid_enclosure
              noiseband: 0.10
              negative_output: -75%
```

```Python Traceback
2021-06-16 09:15:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 214, in on_login
    entity_infos, services = await cli.list_entities_services()
  File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/client.py", line 137, in list_entities_services
    entities.append(cls(**kwargs))
  File "<attrs generated init aioesphomeapi.model.ClimateInfo>", line 9, in __init__
    self.supported_modes = __attr_converter_supported_modes(supported_modes)
  File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/model.py", line 245, in _convert_climate_modes
    return [ClimateMode(val) for val in value]
  File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/model.py", line 245, in <listcomp>
    return [ClimateMode(val) for val in value]
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 6 is not a valid ClimateMode
```
