### ISSUE TITLE
led turn on example?

### ISSUE THREAD

**Issue by jaggzh** [esphome/aioesphomeapi#365]
It's hard to find examples online!  :)

Anyone know how I'd turn an LED on?  (Eventually one of a few relays)?

Here's my yaml and python code.
(With some stuff cut from the yaml, like time-server, for brevity):
---- sprinklers.yaml ------------------
```yaml
esphome:
  name: sprinklers

esp8266:
  board: nodemcuv2

# Enable logging
logger:

api:
  password: "meowmix"
  reboot_timeout: 0s
  services:
    - service: yellow_on
      then:
        - switch.turn_on: yellow_pin

ota:
  password: "meowmix"

captive_portal:

switch:
- platform: gpio
  pin: D8
  id: yellow_pin
  # mode:
  #   input: false
  #   pullup: false
- platform: gpio
  pin: D3
  id: green_pin
- platform: gpio
  id: red_pin
  pin:
    number: D4
    mode: OUTPUT
  restore_mode: ALWAYS_OFF 
  on_turn_on:
    - logger.log: "RED On!"
  on_turn_off:
    - logger.log: "RED Off!"

- platform: template
  name: "Yellow LED"
  optimistic: yes
  id: yellowled
  turn_on_action:
  - while:
      condition:
        lambda: 'return true;'
      then:
      - switch.turn_on: yellow_pin
      - delay: 500ms 
      - switch.turn_off: yellow_pin
      - delay: 500ms
  turn_off_action:
  - switch.turn_off: yellow_pin

# - platform: template
#   name: "Red LED"
#   optimistic: yes
#   id: redled
#   turn_on_action:
#   - switch.turn_on: red_pin
#   turn_off_action:
#   - switch.turn_off: red_pin

- platform: template
  name: "Green LED"
  optimistic: yes
  id: greenled
  turn_on_action:
  - switch.turn_on: green_pin
  turn_off_action:
  - switch.turn_off: green_pin
```

---------- sprinkler_led_on_test.py -------------------
```python
#!/usr/bin/env python

import aioesphomeapi
from aioesphomeapi.model import (UserService)
import asyncio
import ipdb

async def main():
	"""Connect to an ESPHome device and get details."""

	# Establish connection
	api = aioesphomeapi.APIClient("sprinklers.local", 6053, "meowmix")
	await api.connect(login=True)

	# List all entities of the device
	entities = await api.list_entities_services()
	print("\nEntities:")
	for eli, entlist in enumerate(entities):
		for ei, ent in enumerate(entlist):
			print(f"[{eli}][{ei}] {ent}")

	service = UserService(
			name="yellow_on",
			)
	await api.execute_service(service, data={})
	#ipdb.set_trace()
	# print( [f" {i}\n" for i in entities])

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
